name: Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Cache MkDocs dependencies
        uses: actions/cache@v3
        with:
          path: .cache
          key: ${{ runner.os }}-mkdocs-${{ hashFiles('mkdocs.yml') }}
          restore-keys: |
            ${{ runner.os }}-mkdocs-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            mkdocs-material \
            mkdocs-awesome-pages-plugin \
            pymdown-extensions \
            pygments
      
      - name: Test documentation build
        run: mkdocs build --strict
      
      - name: Build and deploy documentation
        run: mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}